version: '2'

volumes:
    database_data:
        driver: local

services:
  nginx:
      build:
        context: .
        dockerfile: web.dockerfile
      ports:
          - 8080:80
  mongodb:
      image: mongo:3.4.6
      expose:
        - 27017
      volumes:
        - /srv/docker/mongodb:/var/lib/mongodb
  php:
      build:
        context: .
        dockerfile: app.dockerfile
      expose:
          - 9000
      environment:
          - "DB_HOST=mongodb"
          - "DB_PORT=27017"
      links:
          - mysql
          - mongodb
